"""Special edition constants.

This module defines special edition types (Director's Cut, Extended Edition, etc.)
and their aliases for detection in filenames.
"""

SPECIAL_EDITIONS = {
    "Theatrical Cut": ["Theatrical Cut", "Theatrical Reconstruction"],
    "Director's Cut": ["Director's Cut", "Director Cut"],
    "Extended Cut": ["Extended Cut", "Ultimate Extended Cut", "Extended Edition", "Ultimate Extended Edition"],
    "Special Edition": ["Special Edition"],
    "Open Matte": ["Open Matte"],
    "Collector's Edition": ["Collector's Edition"],
    "Criterion Collection": ["Criterion Collection"],
    "Anniversary Edition": ["Anniversary Edition"],
    "Redux": ["Redux"],
    "Final Cut": ["Final Cut"],
    "Alternate Cut": ["Alternate Cut"],
    "International Cut": ["International Cut"],
    "Restored Edition": [
        "Restored Edition",
        "Restored Version",
        "4K Restoration",
        "Restoration",
    ],
    "Remastered": ["Remastered", "Remaster", "HD Remaster"],
    "Unrated": ["Unrated"],
    "Uncensored": ["Uncensored"],
    "Definitive Edition": ["Definitive Edition"],
    "Platinum Edition": ["Platinum Edition"],
    "Gold Edition": ["Gold Edition"],
    "Diamond Edition": ["Diamond Edition"],
    "Steelbook Edition": ["Steelbook Edition"],
    "Limited Edition": ["Limited Edition"],
    "Deluxe Edition": ["Deluxe Edition"],
    "Premium Edition": ["Premium Edition"],
    "Complete Edition": ["Complete Edition"],
    "AI Remaster": ["AI Remaster", "AI Remastered"],
    "Upscaled": [
        "AI Upscaled",
        "AI Enhanced",
        "AI Upscale",
        "Upscaled",
        "Upscale",
        "Upscaling",
    ],
    "Director's Definitive Cut": ["Director's Definitive Cut"],
    "Extended Director's Cut": ["Extended Director's Cut", "Ultimate Director's Cut"],
    "Original Cut": ["Original Cut"],
    "Cinematic Cut": ["Cinematic Cut"],
    "Roadshow Cut": ["Roadshow Cut"],
    "Premiere Cut": ["Premiere Cut"],
    "Festival Cut": ["Festival Cut"],
    "Workprint": ["Workprint"],
    "Rough Cut": ["Rough Cut"],
    "Special Assembly Cut": ["Special Assembly Cut"],
    "Amazon Edition": ["Amazon Edition", "Amazon", "Amazon Prime Edition", "Amazon Prime"],
    "Netflix Edition": ["Netflix Edition"],
    "HBO Edition": ["HBO Edition"],
    "VHS Source": ["VHSRecord", "VHS Record", "VHS Rip", "VHS", "VHS-Rip"],
}
